DROP TABLE IF EXISTS Menu;

CREATE TABLE Menu
( Menu_id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  User_id MEDIUMINT UNSIGNED NOT NULL,
  Date DATE NOT NULL,
  Category_id SMALLINT UNSIGNED NOT NULL,
  Recipe_id MEDIUMINT UNSIGNED NOT NULL,
  CONSTRAINT menu_pk
    PRIMARY KEY  (Menu_id),
  CONSTRAINT fk_recipe_menu
    FOREIGN KEY (recipe_id)
    REFERENCES Recipes(Recipe_id)
    ON DELETE CASCADE,
  CONSTRAINT fk_category 
    FOREIGN KEY (Category_id)
    REFERENCES Categories(Category_id)
    ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

-- EXIT;