DROP TABLE IF EXISTS Units;

CREATE TABLE Units
( Unit_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  UnitName VARCHAR(40) NOT NULL,
  Description varchar(255),  
  CONSTRAINT unit_pk
    PRIMARY KEY  (Unit_id),
    UNIQUE KEY ix_unit (UnitName)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

-- EXIT;